### ISSUE TITLE
Исходники страниц

### ISSUE THREAD

**Issue by Bevaz** [lessworks/translation#3]
Мы подготовили перевод обзорной страницы с принципами: https://less.works/ru/less/principles/overview.html

Как лучше выкладывать перевод. Где брать исходники страниц для перевода?

**Comment by bustor** [comment]
@av0r0nin писал мне в мессенджере: "К каждой карточке [trello] прикреплены файлы md, которые нужно переводить. Итогом перевода должен стать файл в md разметке. Перед началом перевода **запроси у @terry713 последнюю версию md файла**, так как периодически англоязычный контент сайта обновляется."

**Comment by bustor** [comment]
Про "как лучше выкладывать перевод" - вот ребята в папке "principles" (https://github.com/lessworks/translation/tree/master/principles) создавали файлы с именами "systems_thinking ru.md" (https://github.com/lessworks/translation/blob/master/principles/systems_thinking%20ru.md), "queueing_theory.ru.md" (https://github.com/lessworks/translation/blob/master/principles/queueing_theory.ru.md). 

Думаю, имеет смысл выкладывать файлы и называть их по подобию.

**Comment by Bevaz** [comment]
> запроси у @terry713 последнюю версию md файла

Github такого пользователя не знает

**Comment by bustor** [comment]
Антон @bevzuk запрашивал у него вот тут в карточке: https://trello.com/c/8e2to4Zl/28-http-lessworks-less-principles-systemsthinkinghtml

**Comment by Bevaz** [comment]
У меня нет доступа к этой карточке в трелло

**Comment by bustor** [comment]
Мне доступы в trello давал @av0r0nin. Попробуй ему написать в FB messanger, например. Вот его профиль в fb - https://www.facebook.com/av0r0nin

**Comment by bevzuk** [comment]
Исходники страниц запрашивайте у меня или Алексея Воронина
