### ISSUE TITLE
Общая терминология

### ISSUE THREAD

**Issue by bustor** [lessworks/translation#4]
Мы не хотим использовать **единую терминологию** при переводе? Чтобы на этапе финальной сборки всего сайта минимизировать трудозатраты. 

Я бы сделал какой-то единый глоссарий. Но не глоссарий фреймворка, который потом, например, можно будет вывалить на конечных читателей, а внутренний глоссарий рабочей группы - отвечающий на вопрос: "Как правильно какие термины переводить?".

Вот например первое же предложение в https://less.works/less/framework/introduction.html:

> There are two ways of constructing a [design]

Не надо ли нам договориться, как будем переводить слово **construction**, a как - **design**?

Да и при ревью переводов будет эталон - с которым можно сравнивать.

Может у кого-то есть знакомые переводчики, которые могут поделиться наработанными практиками перевода текста группой?

**Comment by bevzuk** [comment]
По-моему переводчики тут не особо помогут, потому что с общей лексикой и сами справимся, а в профессиональной они не шарят, если только нам не повезет найти переводчика, который шарит в LeSS, но пока что таких нет :)
А вот для перевода терминов LeSS, Scrum и Agile словарик нужен и он уже есть. 
https://github.com/lessworks/translation/blob/master/dictionary.txt

**Comment by bustor** [comment]
Про переводчиков - я писал именно с точки зрения шаринга *best practises в процессе группового перевода*. Понятно, что и без них справимся, не rocket science. :) Просто если есть возможность воспользоваться чужим опытом - предпочитаю таки пользоваться. (Я не настаиваю на поиске переводчиков, просто раскрыл свою позицию).

OK, со словарём понял. Буду наполнять. 

Но пока в словаре маловато терминов, мне кажется. Я очень бегло просмотрел первые несколько предложений Introduction, но уже:
* договорился бы о переводе терминов construction и design (хотя они приведены в предисловии, может там во всём LeSS они дальше и не используются ...),
* увидел, что термин framework переведён в нарушение словаря.

**Comment by bevzuk** [comment]
Словарик терминов тут https://github.com/lessworks/translation/blob/master/dictionary.txt
Предлагаю при переводе в него заглядывать и пополнять.
Особенно важно чтобы в нем были термины LeSS, чтобы мы все переводили их одинаково, потому что они часто встречаются в разных местах сайта.
